name: Trigger auto deployment for aca-votingapp-demo-we

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/aca-votingapp-demo-we-AutoDeployTrigger-d09cbb18-b525-4ebe-be8f-b5e4944af839.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrjskubeeducwe.azurecr.io
          username: ${{ secrets.ACAVOTINGAPPDEMOWE_REGISTRY_USERNAME }}
          password: ${{ secrets.ACAVOTINGAPPDEMOWE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrjskubeeducwe.azurecr.io/aca-votingapp-demo-we:${{ github.sha }}
          file: ./azure-vote/Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACAVOTINGAPPDEMOWE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n aca-votingapp-demo-we -g rg-demo-aca-prd-fc --server acrjskubeeducwe.azurecr.io --username  ${{ secrets.ACAVOTINGAPPDEMOWE_REGISTRY_USERNAME }} --password ${{ secrets.ACAVOTINGAPPDEMOWE_REGISTRY_PASSWORD }}
            az containerapp update -n aca-votingapp-demo-we -g rg-demo-aca-prd-fc --image acrjskubeeducwe.azurecr.io/aca-votingapp-demo-we:${{ github.sha }}
